language: r

cache: packages

before_install:
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_cran(c("golem", "bookdown"))'
  
script:
  - Rscript -e 'bookdown::render_book("index.rmd")'
  
