language: r
cache: packages
dist: trusty
sudo: required
  
env:
  global:
  - MAKEFLAGS="-j 2"
  
install:
  - Rscript -e 'install.packages("remotes")'
  - Rscript -e 'remotes::install_cran(c("golem", "bookdown"))'
  
script:
  - make html

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
