on:
  pull_request:
    branches:
      - master

env: 
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  
name: renderbookpr

jobs:
  bookdown:
    
    name: Render-Book
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          crayon.enabled: 'FALSE'
          r-version: '3.6.1'
          
      - uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
          
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install tinytex
        uses: r-lib/actions/setup-tinytex@v2
      
      - name: Install sysreq
        run: sudo apt update && sudo apt install -y gdal-bin git-core libcairo2-dev libgdal-dev libgeos-dev libgeos++-dev libgit2-dev libpng-dev libssh2-1-dev libssl-dev libudunits2-dev libxml2-dev make pandoc pandoc-citeproc zlib1g-dev libmagick++-dev libssl-dev libsasl2-dev
        
      - name: Pulling hexmake
        run: docker pull colinfay/hexmake
        
      - uses: nanasess/setup-chromedriver@master

      - name: Install rmarkdown, bookdown and sysfonts
        run: Rscript -e 'install.packages(c("sysfonts", "rmarkdown","bookdown"), Ncpus = 4)'

      - name: Before build
        run: Rscript prep.R
          
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
          
      - uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site/
